!!edu.umn.amicus.config.AmicusPipelineConfiguration
_pipelineName: Example Amicus pipeline
allSystemsUsed:
- {_systemName: gold, dataPath: /Users/gpfinley/hermes/home/gpfinley/annotations/manual-annotations,
  readFromView: SystemView, saveIntoView: GoldView}
- {_systemName: biomedicus, dataPath: /Users/gpfinley/hermes/home/gpfinley/annotations/biomedicus-1.6.0-october2016,
  readFromView: SystemView, saveIntoView: BiomedicusView}
pipelineComponents:
- !!edu.umn.amicus.config.ExporterConfig
  _exporterName: gold exporter
  alignerClass: edu.umn.amicus.aligners.EachSoloAligner
  exporterClass: edu.umn.amicus.exporters.EachSoloTsvExporterExporter
  inputs:
  - &id001 {annotationField: acronymAbbrevExpansion, annotationType: edu.umn.biomedicus.type.TokenAnnotation,
    fromView: GoldView, pullerClass: edu.umn.amicus.pullers.EquivalentMapperPuller}
  outputDirectory: data/out/goldExports
- !!edu.umn.amicus.config.ExporterConfig
  _exporterName: biomedicus exporter
  alignerClass: edu.umn.amicus.aligners.EachSoloAligner
  exporterClass: edu.umn.amicus.exporters.EachSoloTsvExporterExporter
  inputs:
  - &id002 {annotationField: text, annotationType: edu.umn.biomedicus.uima.type1_6.Acronym,
    fromView: BiomedicusView, pullerClass: edu.umn.amicus.pullers.EquivalentMapperPuller}
  outputDirectory: data/out/biomedicusExports
- !!edu.umn.amicus.config.CollectorConfig
  input: *id001
  name: gold collector
  outPath: null
  summarizerClass: edu.umn.amicus.summarizers.CounterSummarizer
- !!edu.umn.amicus.config.CollectorConfig
  input: *id002
  name: biomedicus collector
  outPath: null
  summarizerClass: edu.umn.amicus.summarizers.CounterSummarizer
- !!edu.umn.amicus.config.MergerConfig
  _mergerName: acronym eval merger
  alignerClass: edu.umn.amicus.eval.EvalPerfectOverlapAligner
  inputs:
  - *id001
  - *id002
  outputs:
  - {annotationField: field, annotationType: edu.umn.amicus.SingleFieldAnnotation,
    pusherClass: edu.umn.amicus.eval.EvalMatchPusher, distillerClass: edu.umn.amicus.eval.EvalMatchDistiller,
    writeView: EvalView}
- !!edu.umn.amicus.config.CollectorConfig
  input: {annotationType: edu.umn.amicus.EvalAnnotation,
    fromView: EvalView, pullerClass: edu.umn.amicus.eval.EvalMatchPuller}
  name: eval collector
  outPath: null
  summarizerClass: edu.umn.amicus.eval.EvalPrfSummarizerer
xmiOutPath: /Users/gpfinley/hermes/home/gpfinley/xmi-export-out-temp
