!!edu.umn.amicus.config.AmicusPipelineConfigurationpipelineName: simpletest

inputNames: [ctakes]
inputDirectories: [data/ctakes]
inputViews: [_InitialView]

outPath: data/example_out

pipelineComponents:
- _mergerName: test

  alignerClass: edu.umn.amicusigners.PerfectOverlapAligner

  inputs:
  - {annotationField: ontologyConceptArr, annotationType: org.apache.ctakes.typesystem.type.textsem.IdentifiedAnnotation,
    fromView: ctakes, pullerClass: edu.umn.amicusllersesCuiTransformer}

  outputs:
  - {annotationField: field, annotationType: edu.umn.amicusngleFieldAnnotation,
    writeView: ctakesView}


- _mergerName: test2

  inputs:
  - {annotationField: field, annotationType: edu.umn.amicusngleFieldAnnotation, fromView: ctakes,
    pullerClass: edu.umn.amicusllersonceptTransformer}

  outputs:
  - {annotationField: field, annotationType: edu.umn.amicusngleFieldAnnotation}

# TODO: allow pulling from specific views, not just systems

#    creatorClass: edu.umn.amicus.pushers.SimplePusher, distillerClass: edu.umn.amicus.distillers.PriorityDistiller,
