!!edu.umn.ensembles.config.EnsemblesPipelineConfiguration

_pipelineName: simpletest

inputNames: [ctakes]
inputDirectories: [data/ctakes]
inputViews: [_InitialView]

outPath: data/example_out

mergerConfigurations:
- _mergerName: test

  alignerClass: edu.umn.ensembles.aligners.PerfectOverlapAligner

  inputs:
  - {annotationField: ontologyConceptArr, annotationType: org.apache.ctakes.typesystem.type.textsem.IdentifiedAnnotation,
    fromView: ctakes, transformerClass: edu.umn.ensembles.pullersesCuiTransformer}

  outputs:
  - {annotationField: field, annotationType: edu.umn.ensembles.SingleFieldAnnotation,
    writeView: ctakesView}


- _mergerName: test2

  inputs:
  - {annotationField: field, annotationType: edu.umn.ensembles.SingleFieldAnnotation, fromView: ctakes,
    transformerClass: edu.umn.ensembles.pullersonceptTransformer}

  outputs:
  - {annotationField: field, annotationType: edu.umn.ensembles.SingleFieldAnnotation}

# TODO: allow pulling from specific views, not just systems

#    creatorClass: edu.umn.ensembles.pushers.SimplePusher, distillerClass: edu.umn.ensembles.distillers.PriorityDistiller,
