!!edu.umn.amicus.summary.ElasticsearchIndexingSummarizer$Config
esFieldNames: [ctakesCuis, clampCuis, biomedicusCuis]
esHost: "localhost"
esIndexName: "amicusdocs"
esTypeName: "amicusdoc"
esIdField: "docId"
esPort: 9300
